init:
    define main_menu_music = "audio/music/main_menu.mp3"
    define snake_game_music = "audio/music/snake_game.mp3"
    define ringtone_music = "audio/music/ringtone.mp3"
    define bubble_shooter_game_music= "audio/music/bubble_shooter_game.mp3"
    
    define snake_eating_sound = "audio/sound/snake_eating.mp3"
    define snake_coming_sound = "audio/sound/snake_coming.mp3"
    define car_pass_by_sound = "audio/sound/car_pass_by.mp3"
    define shoot_sound = "audio/sound/shoot.mp3"
    define explode_sound="audio/sound/explode.mp3"
    define touch_sound="audio/sound/touch.mp3"
    define lose_sound="audio/sound/lose.mp3"
    define win_sound="audio/sound/win.mp3"
    define hahaha_sound="audio/sound/hahaha.mp3"
    define humhum_sound="audio/sound/humhum.mp3"
    define what_sound="audio/sound/what.mp3"
    define hahaha_woman_sound="audio/sound/hahaha_woman.mp3"
    define huh_sound="audio/sound/huh.mp3"
    define wow_sound="audio/sound/wow.mp3"
    define yeah_sound="audio/sound/yeah.mp3"
    define sigh_sound="audio/sound/sigh.mp3"
    define hum_sound="audio/sound/hum.mp3"
    define ok_sound="audio/sound/ok.mp3"


